#ifndef nodenames_h
#define nodenames_h
/*
 * Automatically generated by ./mknodenames.sh
 * DO NOT EDIT. Do Not 'cvs add'.
 */

#ifndef NODENAMES_H_INCLUDED
#define NODENAMES_H_INCLUDED

#ifdef DEBUG

#ifdef DEFINE_NODENAMES
STATIC const char * const NodeNames[27 + 1] = {
	"NSEMI",
	"NCMD",
	"NPIPE",
	"NREDIR",
	"NBACKGND",
	"NSUBSHELL",
	"NAND",
	"NOR",
	"NIF",
	"NWHILE",
	"NUNTIL",
	"NFOR",
	"NCASE",
	"NCLISTCONT",
	"NCLIST",
	"NDEFUN",
	"NARG",
	"NTO",
	"NCLOBBER",
	"NFROM",
	"NFROMTO",
	"NAPPEND",
	"NTOFD",
	"NFROMFD",
	"NHERE",
	"NXHERE",
	"NNOT",
	"NDNOT",
};
#else
extern const char * const NodeNames[27 + 1];
#endif

#define NODETYPENAME(type) \
	((unsigned)(type) <= 27 ? NodeNames[(type)] : "??OOR??")

#define NODETYPE(type)	NODETYPENAME(type), (type)
#define PRIdsNT		"s(%d)"

#else /* DEBUG */

#define NODETYPE(type)	(type)
#define PRIdsNT		"d"

#endif /* DEBUG */

#endif /* !NODENAMES_H_INCLUDED */

#endif

