/*
 * This file was generated by the mkinit program.
 */

#include "shell.h"
#include "mystring.h"
#include "init.h"
//#include <stdint.h>
//#include <stdint.h>








/*
 * Initialization code.
 */

void
init(void)
{

}



/*
 * This routine is called when an error or an interrupt occurs in an
 * interactive shell and control is returned to the main command loop.
 */

void
reset(void)
{

}



/*
 * This routine is called to initialize the shell to run a shell procedure.
 */

void
initshellproc(void)
{

}
