#define mini_buf 40000
#define HEADERGUARDS
#define mini_start 
#define INCLUDESRC
#define mini_abort generate
#define mini_access generate
#define mini_atoi generate
#define mini_chdir generate
#define mini_close generate
#define mini_closedir generate
#define mini_dup generate
#define mini_dup2 generate
#define mini_execl generate
#define mini_execve generate
#define mini_exit generate
#define mini_fclose generate
#define mini_fcntl generate
#define mini_fdopen generate
#define mini_fileno generate
#define mini_fork generate
#define mini_fprintf generate
#define mini_fputs generate
#define mini_free generate
#define mini_fstat generate
#define mini_getenv generate
#define mini_getgid generate
#define mini_getgroups generate
#define mini_gethostname generate
#define mini_getpgrp generate
#define mini_getpid generate
#define mini_getpwnam generate
#define mini_getpwuid generate
#define mini_getuid generate
#define mini_ioctl generate
#define mini_isatty generate
#define mini_kill generate
#define mini_lseek generate
#define mini_lstat generate
#define mini_malloc generate
#define mini_memcmp generate
#define mini_memcpy generate
#define mini_memmove generate
#define mini_memset generate
#define mini_open generate
#define mini_opendir generate
#define mini_pipe generate
#define mini_printf generate
#define mini_putchar generate
#define mini_qsort generate
#define mini_raise generate
#define mini_read generate
#define mini_readdir generate
#define mini_realloc generate
#define mini_rewinddir generate
#define mini_setenv generate
#define mini_setgid generate
#define mini_setpgid generate
#define mini_setuid generate
#define mini_sigaction generate
#define mini_sigaddset generate
#define mini_sigemptyset generate
#define mini_signal generate
#define mini_sigprocmask generate
#define mini_snprintf generate
#define mini_stat generate
#define mini_strcasecmp generate
#define mini_strcat generate
#define mini_strchr generate
#define mini_strcmp generate
#define mini_strcpy generate
#define mini_strdup generate
#define mini_strerror generate
#define mini_strlcpy generate
#define mini_strlen generate
#define mini_strncasecmp generate
#define mini_strncmp generate
#define mini_strstr generate
#define mini_strtok generate
#define mini_strtol generate
#define mini_strtoll generate
#define mini_tcgetattr generate
#define mini_tcsetattr generate
#define mini_time generate
#define mini_umask generate
#define mini_unlink generate
#define mini_waitpid generate
#define mini_write generate
#define mini_getgrent generate
#define mini_stpcpy generate
#define mini_uname generate
#define mini_setjmp
#define mini_errno generate
#define mini_times generate
#define mini_getrlimit generate
#define mini_geteuid generate
#define mini_getegid generate
#define mini_setrlimit generate
#define mini_dup3 generate
#define mini_killpg generate
#define mini_bsearch generate
#define mini_locale_dummies generate
#define mini_strcspn generate
#define mini_strspn generate
#define mini_strtoimax generate
#define mini_tcgetpgrp generate
#define mini_tcsetpgrp generate
#define mini_getopt
#define mini_sys_signame generate
#define mini_bsd_timespec generate
#define mini_bsd_definitions generate
