puts("\n"
"Program description: die is a UNIX utility which will allow you to kill a \n"
"                     job by process name, instead of number.  Instead of  \n"
"                     having to do a 'ps -x' to find the process you want, \n"
"                     look up the PID number, and do a 'kill <PID number>', \n"
"                     you can just do 'die <process>'.  If you are running \n"
"                     more than one process of the same name, die will \n"
"                     prompt you on wether or not to kill each one, unless \n"
"                     you used the -f switch, in which case die runs amok \n"
"                     through the process table, killing all your matching \n"
"                     processes, with sickening glee and enthusiasm.  \n"
"                   \n"
"                     You can call die with any number of commands (processes) \n"
"                     to kill.  If die does not find a match for an argument, \n"
"                     it will silently terminate.  If it does find a match, \n"
"                     it will just as silently kill the job.  You will probably                       recieve a message from UNIX though, telling you that a \n"
"                     job has just been killed. \n"
"\n"
"Legal stuff:         die is freeware.  I retain all rights to the code, but \n"
"                     you are free to use or alter it in any way you like, as  \n"
"                     long as any program or application it is used in (or with) \n"
"                     is freeware as well, and I am given credit for my work.                         If for some unfathonable reason, you want to use this code \n"
"                     in a commercial software package, send me some mail or  \n"
"                     something and, assuming I haven't won the lottery or had \n"
"                     a rich uncle kick the bucket, I'll tailor something to  \n"
"                     your exact specifications.  For a fee, of course!  :-) \n"
"\n"
"Execution: die [-cfhil] [process(es)]  \n"
"           \n"
"           Running die with no arguments will give you the option list. \n"
" \n"
"           Options (switches): \n"
" \n"
"           c = Careful mode.  die will prompt you on wether or not to kill \n"
"               each and every matching process it finds. \n"
" \n"
"           i = Interactive mode.  die will give you a list of the processes \n"
"               which are running, ask you which ones to kill, and ask you \n"
"               which mode to kill them in.  (careful, force, normal, or \n"
"               in the same mode that you killed processes in last time; or \n"
"               if this is the first \"loop\", in the mode that you called \n"
"               die with.)  If you specify processes to kill when starting \n"
"               die in interactive mode, die will take care of them first, \n"
"               using the mode you specify at the command line. \n"
" \n"
"           f = Force mode.  Die will take the process names given at the \n"
"               command line and kill every occurence of them in the  \n"
"               process table, *without* asking permission.  In other  \n"
"               words, 'die -f sh' is a real quick way to log out.  ;-) \n"
" \n"
"           l = List mode.  die will give you a listing of the processes  \n"
"               currently running before killing anything off.  Calling die \n"
"               with -l and no processes will simply give you the process \n"
"               list. \n"
" \n"
"           h = Help mode.  Calling die with -h will bring up a bunch of  \n"
"               helpful info and some other stuff.  (More detailed help \n"
"               than can be obtained by just running die with no (or  \n"
"               invalid) arguments.) \n"
"\n"
"VERY, VERY IMPORTANT:  die cannot, and therefore does not kill your processes\n"
"                       by 'program name'.  It looks for substring matches in \n"
"                       the process table (ps -x).  This can be both good or\n"
"                       bad.  \n"
"\n"
"     The good:  Someone breaks into your account, and they are on ttyp0.  You\n"
"                type 'die -f ttyp0' and they're toast, along with anything\n"
"                they may have been running.\n"
"\n"
"     The bad:  You are editing the file, 'tin.txt'.  You are also in tin, \n"
"               reading alt.cows.moo.moo.moo.  Tin locks up, so you throw\n"
"               it in the background, and type 'die -f tin'.  Guess what?\n"
"               I hope you saved 'tin.txt' recently, because your revisions \n"
"               just got a one-way ticket to /dev/null.  Obviously, if you\n"
"               had just used 'die tin', it would have asked for a confirmation \n"
"               on both 'tin' and 'vi tin.txt', and you would have said, \n"
"               \"Wow, what a great program!  I think I'll put Jon in my will!\"\n"
"               Just keep your wits about you, and you will be fine.\n"
"\n"
"      The ugly:  You just leave that to me, ok?\n"
"\n"
"\n"
"For more information, see 'die.doc'.\n"
"\n"
"You can obtain the latest version of die via WWW at: \n"
"\n"
"   http://www.cs.fredonia.edu/~stei0302/PUB/SOURCE/MYSTUFF/ \n"
"\n"
"Author:  Jon N. Steiger / stei0302@cs.fredonia.edu\n"
"\n"
"Note:  If you use/like die, please take a moment to drop\n"
"       me a note.  I'd like to know wether or not I just\n"
"       wasted my time on this thing.  :-)\n"
"\n"
"");\n"
"\n"
"\n"
