#define mini_buf 4096
#define HEADERGUARDS
#define mini_start 
#define INCLUDESRC
#define mini_globals generate
#define mini_ewrites generate
#define mini_writes generate
#define mini_printfs generate
#define mini_unlockpt generate
#define mini_grantpt generate
#define mini_fdopen generate
#define mini_getchar generate
#define mini_setbuf generate
#define mini_setvbuf generate
#define mini_wait generate
#define mini_waitpid generate
#define mini_itodec generate
#define mini_errno generate
#define mini_environ generate
#define mini_system generate
#define mini_prints generate
#define mini_atoi generate
#define mini_chdir generate
#define mini_close generate
#define mini_dup generate
#define mini_execve generate
#define mini_fclose generate
#define mini_fork generate
#define mini_fprintf generate
#define mini_fprintfs generate
#define mini_fputs generate
#define mini_free generate
#define mini_fstat generate
#define mini_getc generate
#define mini_getenv generate
#define mini_getgid generate
#define mini_getpgrp generate
#define mini_getpid generate
#define mini_getuid generate
#define mini_ioctl generate
#define mini_isatty generate
#define mini_kill generate
#define mini_lseek generate
#define mini_malloc generate
#define mini_malloc_brk generate
#define mini_mkdir generate
#define mini_open generate
#define mini_perror generate
#define mini_pipe generate
#define mini_printf generate
#define mini_read generate
#define mini_select generate
#define mini_setsid generate
#define mini_setuid generate
#define mini_signal generate
#define mini_sleep generate
#define mini_sprintf generate
#define mini_stat generate
#define mini_strcmp generate
#define mini_strcpy generate
#define mini_strlen generate
#define mini_strncmp generate
#define mini_time generate
#define mini_vfork generate
#define mini_write generate
#define mini_fwrites generate
#define mini_chmod generate
#define mini_utime generate
